name: Bug report
description: Something isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: When I run `gh buddy create-branch`, it...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: I expected it to...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `gh buddy ...`
        2. See error
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        - OS: macOS 14 / Ubuntu 22.04 / Windows 11
        - gh version: 2.x.x
        - gh-buddy version: v0.x.x
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant output or logs
      render: shell
    validations:
      required: false
